spring:
    profiles:
        active: local

---
spring:
    profiles: mysql
    datasource:
        hikari:
            jdbc-url: jdbc:mysql://localhost:3306/test
            username: test
            password: test
            driver-class-name: com.mysql.jdbc.Driver
